version: "3.6"

services:
    nftapp:
        container_name: nftapp
        image: nikolaik/python-nodejs:python3.7-nodejs16-alpine
        restart: always
        # env_file: .env
        volumes:
            - ./:/src
        working_dir: /src
        # ports:
        #     - 3000:3000
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command:
            - /bin/sh
            - -c
            - |
                npm i
                sleep 999999999
                npm run start